steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: ${CI_COMMIT_SOURCE_BRANCH/\//-}
    secrets: [ docker_username, docker_password ]
when:
  branch: feature/*
  event: push
